version: "3.3"
services:
  mongodb:
    image : mongo:7.0
    container_name: cryptobotmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: datascientest
      MONGO_INITDB_ROOT_PASSWORD: dst123
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
